version: '3'
services:
  elasticsearch:
    container_name: elasticsearch-1
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    environment:
      - node.name=elasticsearch1
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=elasticsearch1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256M -Xmx256M"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - network.host=_eth0_
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
  kibana:
    container_name: kibana-1
    image: docker.elastic.co/kibana/kibana:7.6.0
    ports:
      - "5601:5601"